### ISSUE TITLE
Inkbunny not downloading full resolution images

### ISSUE THREAD

**Issue by MystifyingShadow** [solorey/Art-Saver#5]
Hi, It seems that Art-Saver is not dowloading the full resolution images from Inkbunny.

**Comment by solorey** [comment]
It seems downloading images from Inkbunny does not work when not logged in. I've fixed some functionality to allow downloading to work in v1.3.2.

**Comment by MystifyingShadow** [comment]
With v1.3.2 it seems to be downloading more files when logged in, but still not at the full resolution.
For example this image:
https://inkbunny.net/s/2192089
Art-Saver is downloading a 1.40MB image with the resolution 733 x 1840, but if I download directly from the page I get an image with 2.41MB and a resolution of 1024 x 2571.

**Comment by solorey** [comment]
There may be an issue with the order in what download links are found. The 733 x 1840 image should be the last resort if the full size is not found. I've added a new commit to explicitly set the order of checking as they were previously all looked for at the same time. Try downloading this repository with the patch and [install it temporarily](https://extensionworkshop.com/documentation/develop/temporary-installation-in-firefox/) to see if it works.

**Comment by MystifyingShadow** [comment]
Yes, it seems to have fixed that problem.
Now sometimes when downloading all of the images inside a page a User gallery, I get the error [art saver] TypeError: "arg1.querySelector is not a function"

**Comment by solorey** [comment]
You will have to be more specific on when/where the error shows up and what you were doing. This is an error in trying to find something on the page.

**Comment by MystifyingShadow** [comment]
The full message on the console is:
`[art saver] TypeError: "arg1.querySelector is not a function"
    $ moz-extension://51100452-a1bf-4016-8b0c-0bd7db8b5178/content_scripts/selectors.js:2
    getPageMeta moz-extension://51100452-a1bf-4016-8b0c-0bd7db8b5178/content_scripts/inkbunny.js:217
    createDownloads moz-extension://51100452-a1bf-4016-8b0c-0bd7db8b5178/content_scripts/inkbunny.js:258`

**Comment by solorey** [comment]
Interesting. Seems to be an issue with the response of the additional pages of a submission.

I can't replicate the issue myself so to debug this, create a breakpoint by clicking on (line 257 for you) and try to download a submission that gives the error.
![debug](https://user-images.githubusercontent.com/48976970/86072870-394d4b80-ba48-11ea-8f07-4e85dc66d52d.png)
Tell me whats in the results.

**Comment by MystifyingShadow** [comment]
results[
	Error 429:{
		columnNumber: 15
		fileName: "moz-extension://51100452-a1bf-4016-8b0c-0bd7db8b5178/content_scripts/main.js"
		lineNumber: 79
		message: "https://inkbunny.net/s/2136375"
		name: "Error 429"
		stack: "fetcher@moz-extension://51100452-a1bf-4016-8b0c-0bd7db8b5178/content_scripts/main.js:79:15\n"
	}
]

**Comment by solorey** [comment]
Looks like you are getting `Error 429: Too Many Requests`
This can happen when someone sends too many requests to a site in a given amount of time. The way this extension works for Inkbunny is that it sends a request per submission you want to download plus another request per page if the submission has multiple pages. When this starts happening try taking a break and slowing down attempts to download.

**Comment by MystifyingShadow** [comment]
I think the problem is when you try to download for example the top upload page, it has 56 images. And when I press Download it tries to download all of them at the same time, maybe adding a timer between each request would fix the error?

**Comment by solorey** [comment]
Added a new commit that adds a timer between requests for additional pages of a submission when Error 429 is received.

**Comment by MystifyingShadow** [comment]
Nice, it seems that everything is working now :).

**Comment by solorey** [comment]
v1.3.3 released with these changes.
